[[language]]
name ="python"
language-id ="python"
language-servers = ["pyright"]
auto-format = true
formatter = { command = "black", args = ["-l","120", "--quiet", "-"] }
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi", "py3", "pyw", "ptl", "pyx", "pxd", "pxi"]
shebangs = ["python", "python3"]
roots = ["setup.py", "setup.cfg", "pyproject.toml"]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
